class Offsets:
  PLAYER_PTR = [0x1ACD758, 0]
  GAME_DATA_MANAGER_PTR = [0x1D278F0]
  HP_OFFSET = PLAYER_PTR + [0x3E8]
  MAX_HP_OFFSET = PLAYER_PTR + [0x3EC]
  STAMINA_OFFSET = PLAYER_PTR + [0x3F8]
  MAX_STAMINA_OFFSET = PLAYER_PTR + [0x3FC]
  LEVEL_OFFSET = PLAYER_PTR + [0xDA0]
  SOULS_OFFSET = GAME_DATA_MANAGER_PTR + [0xDA4]
  IN_GAME_OFFSET = 0x1D260A8

class GameData:
  HP = "HP"
  MAX_HP = "MAX_HP"
  STAMINA = "STAMINA"
  MAX_STAMINA = "MAX_STAMINA"
  LEVEL = "LEVEL"
  SOULS = "SOULS"
  IN_GAME = "IN_GAME"
  IN_LOADING_SCREEN = "IN_LOADING_SCREEN"
  IS_ALIVE = "IS_ALIVE"